name: Environment deployment

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Deploy Environment dev or stg?'
        required: true 
        type: choice
        options:
          - dev
          - stg
        
jobs:
  dev_env:
    if: github.event.inputs.releaseType == 'dev'
    runs-on: ubuntu-latest    
    environment: dev
    steps:      
    - name: dev secrets
      run: |
        echo ${{ secrets.DEV_SEC }} 

  stg_env:
    needs: [dev_env]
    if: >- 
      github.event.inputs.releaseType == 'stg' &&
      needs.test-api.result == 'success' ||
      needs.test-api.result == 'failure' ||
      needs.test-api.result == 'error'
    runs-on: ubuntu-latest
    environment: stg
    steps:
    - name: stg secrets
      run: |
        echo ${{ secrets.STG_SEC }}
