name: env secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stg

      
jobs:
  dev_env:
    runs-on: ubuntu-latest    
    environment: 
      name: ${{ github.events.inputs.environment }}
      url: https://github.com
    steps:
    - name: dev secrets
      if: ${{ github.events.inputs.environment == 'dev' }}
      run: echo ${{ secrets.DEV_SEC }}

    - name: stg secrets
      if: ${{ github.events.inputs.environment == 'stg' }}
      run: echo ${{ secrets.STG_SEC }}
