name: env secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stg

      
jobs:
  dev_env:
    runs-on: ubuntu-latest    
    environment: dev
    steps:
    - name: print
      run: echo ${{ github.events.inputs.environment }}
      
    - name: dev secrets
      if: ${{ github.events.inputs.environment }} == 'dev'
      run: echo ${{ secrets.DEV_SEC }}

  stg_env:
    runs-on: ubuntu-latest
    environment: stg
    steps:
    - name: stg secrets
      run: echo ${{ secrets.STG_SEC }}
