name: env secrets

on:
  workflow_dispatch:
    inputs:
      ENV:
        type: choice
        required: true
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stg

      
jobs:
  dev_env:
    runs-on: ubuntu-latest    
    environment: ${{ github.event.inputs.ENV }}
    steps:      
    - name: dev secrets
      if: ${{ github.event.inputs.ENV }} == 'dev'
      run: |
        echo ${{ secrets.DEV_SEC }} 

  stg_env:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    steps:
    - name: stg secrets
      if: ${{ github.event.inputs.ENV }} == 'stg'
      run: |
        echo ${{ secrets.STG_SEC }}

